# Generated by Django 4.1.3 on 2022-12-08 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('mobile_no', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=250)),
                ('provider_order_id', models.CharField(max_length=200, unique=True)),
                ('payment_id', models.CharField(max_length=200, unique=True)),
                ('signature_id', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order_id', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_id', models.CharField(max_length=250, unique=True)),
                ('razorpay_id', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.CharField(blank=True, max_length=250, null=True)),
                ('json_data', models.JSONField()),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=200)),
                ('payment_signature', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_payment_id', models.CharField(max_length=250, unique=True)),
                ('transaction_id', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=200)),
                ('transaction_status', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('is_success', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.FloatField(default=0.0)),
                ('signature_verified', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('method', models.CharField(blank=True, max_length=128, null=True)),
                ('amount_refunded', models.FloatField(blank=True, null=True)),
                ('refund_status', models.CharField(blank=True, max_length=128, null=True)),
                ('amount_transferred', models.FloatField(blank=True, default=0.0, null=True)),
                ('captured', models.BooleanField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('card_id', models.CharField(blank=True, max_length=128, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=256, null=True)),
                ('card_network', models.CharField(blank=True, max_length=256, null=True)),
                ('card_type', models.CharField(blank=True, max_length=256, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=256, null=True)),
                ('card_emi', models.BooleanField(default=False)),
                ('card_last4', models.IntegerField(blank=True, null=True)),
                ('card_international', models.BooleanField(blank=True, default=False, null=True)),
                ('bank', models.CharField(blank=True, max_length=128, null=True)),
                ('wallet', models.CharField(blank=True, max_length=128, null=True)),
                ('vpa', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('contact', models.CharField(blank=True, max_length=128, null=True)),
                ('fee', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=128, null=True)),
                ('error_description', models.CharField(blank=True, max_length=128, null=True)),
                ('error_source', models.CharField(blank=True, max_length=128, null=True)),
                ('error_step', models.CharField(blank=True, max_length=128, null=True)),
                ('error_reason', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=256)),
                ('customer_id', models.CharField(blank=True, max_length=256, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=256, null=True)),
                ('json_transaction_data', models.JSONField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='order.payment')),
            ],
        ),
    ]
