# Generated by Django 4.0.3 on 2022-03-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_transactions_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_payment_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
