# Generated by Django 4.0.3 on 2022-03-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_transactions_transaction_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_payment_id',
            field=models.CharField(default=True, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
