# Generated by Django 4.0.3 on 2022-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='json_transaction_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
